theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cleanpng.com%2Fpng-emoji-ios-11-apple-dinosaur-dino-904459%2F&psig=AOvVaw1jdXQAmq_2Wr9VZ4_6gGHa&ust=1710523181812000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCOicsMeh9IQDFQAAAAAdAAAAABAQ
title: Jackie's Amazing Website 
